version: '2'
services:
  db:
    image: mysql:latest
    env_file:
      - .env
    expose:
      - "3306"

  redis:
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - ./data_redis:/data

  web:
    build: .
    container_name: olaplus-api-uservice
    image: olaplus-api-uservice:latest
    working_dir: /local/app
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && uwsgi --http :8000 --module ola_plus.wsgi:application --check-static /static"
    volumes:
      - ./:/local
    ports:
      - "8000:8000"

  doc:
    build: .
    container_name: olaplus-doc-uservice
    image: olaplus-doc-uservice:latest
    working_dir: /local/app
    env_file:
      - .env
    command: bash -c "sphinx-autobuild --poll -p 8001 -H 0.0.0.0 docs docs/_build/html"
    volumes:
      - ./:/local
    ports:
      - "8001:8001"
