# Generated by Django 2.0.1 on 2018-01-08 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HigherEducationInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HigherEducationInstitutionOrigin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningOpportunitySpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('isced_code', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_scheme', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_level', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('higher_education_institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.HigherEducationInstitution')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.OrganizationalUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='learningopportunityspecification',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.OrganizationalUnit'),
        ),
        migrations.AddField(
            model_name='highereducationinstitution',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.HigherEducationInstitutionOrigin'),
        ),
    ]
